# Generated by Django 2.1.7 on 2019-03-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('contact_form_type', models.CharField(max_length=80, verbose_name='contactFormType')),
                ('remove_id', models.PositiveIntegerField(blank=True, default=0, null=True, unique=True, verbose_name='id')),
                ('remove_modification', models.DateTimeField(blank=True, null=True)),
                ('remove_publishDate', models.DateTimeField(blank=True, null=True)),
                ('xlink_href', models.CharField(max_length=280, verbose_name='xlink_href')),
                ('adLinkForJSONP_xlink_href', models.TextField(default=None, verbose_name='adLinkForJSONP_xlink_href')),
                ('adLinkForXMLData_xlink_href', models.TextField(default=None, verbose_name='adLinkForXMLData_xlink_href')),
            ],
            options={
                'db_table': 'apartment',
            },
        ),
    ]
