# Generated by Django 2.1 on 2019-03-22 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentdata', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='contactFormConfiguration_freemiumSettings_duratio',
            new_name='contactFormConfiguration_freemiumSettings_duration',
        ),
    ]
