# Generated by Django 2.1 on 2019-03-22 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentdata', '0002_auto_20190322_1941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='contactDetails_cellPhoneNumberSubscribe',
            new_name='contactDetails_cellPhoneNumberSubscriber',
        ),
    ]
