# Generated by Django 2.1 on 2019-03-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentdata', '0003_auto_20190322_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='contactDetails_cellPhoneNumberCountryCode',
            field=models.CharField(default=None, max_length=100, verbose_name='contactDetails_cellPhoneNumber'),
        ),
        migrations.AlterField(
            model_name='company',
            name='contactDetails_countryCode',
            field=models.CharField(default=None, max_length=100, verbose_name='contactDetails_cellPhoneNumber'),
        ),
        migrations.AlterField(
            model_name='company',
            name='contactDetails_faxNumberCountryCode',
            field=models.CharField(default=None, max_length=100, verbose_name='contactDetails_faxNumberCountryCode'),
        ),
        migrations.AlterField(
            model_name='company',
            name='contactDetails_faxNumberSubscriber',
            field=models.CharField(default=None, max_length=100, verbose_name='contactDetails_faxNumberSubscriber'),
        ),
        migrations.AlterField(
            model_name='company',
            name='contactDetails_salutation',
            field=models.CharField(default=None, max_length=100, verbose_name='contactDetails_salutation'),
        ),
        migrations.AlterField(
            model_name='company',
            name='contactFormConfiguration_addressField',
            field=models.CharField(default=None, max_length=100, verbose_name='contactFormConfiguration_addressField'),
        ),
        migrations.AlterField(
            model_name='company',
            name='contactFormConfiguration_emailAddressField',
            field=models.CharField(default=None, max_length=100, verbose_name='contactFormConfiguration_emailAddressField'),
        ),
        migrations.AlterField(
            model_name='company',
            name='contactFormConfiguration_firstnameField',
            field=models.CharField(default=None, max_length=100, verbose_name='contactFormConfiguration_firstnameField'),
        ),
        migrations.AlterField(
            model_name='company',
            name='contactFormConfiguration_incomeField',
            field=models.CharField(default=None, max_length=100, verbose_name='contactFormConfiguration_incomeField'),
        ),
        migrations.AlterField(
            model_name='company',
            name='contactFormConfiguration_lastnameField',
            field=models.CharField(default=None, max_length=100, verbose_name='contactFormConfiguration_lastnameField'),
        ),
    ]
