# Generated by Django 2.1.7 on 2019-03-18 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentdata', '0004_auto_20190318_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImprintLink',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('imprintLink_xlink_href', models.CharField(default=None, max_length=100, verbose_name='imprintLink_xlink_href')),
            ],
            options={
                'db_table': 'imprintLink',
            },
        ),
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('apartment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_rent', to='rentdata.Apartment')),
            ],
            options={
                'db_table': 'real_estate',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='contactDetails_faxNumberSubscriber',
            field=models.CharField(default=None, max_length=10, verbose_name='contactDetails_faxNumberSubscriber'),
        ),
        migrations.AddField(
            model_name='company',
            name='contactDetails_firstname',
            field=models.CharField(default=None, max_length=30, verbose_name='contactDetails_firstname'),
        ),
        migrations.AddField(
            model_name='company',
            name='contactDetails_homepageUrl',
            field=models.CharField(default=None, max_length=150, verbose_name='contactDetails_homepageUrl'),
        ),
        migrations.AddField(
            model_name='company',
            name='contactDetails_lastname',
            field=models.CharField(default=None, max_length=30, verbose_name='contactDetails_lastname'),
        ),
        migrations.AddField(
            model_name='company',
            name='contactDetails_phoneNumber',
            field=models.CharField(default=None, max_length=50, verbose_name='contactDetails_phoneNumber'),
        ),
        migrations.AddField(
            model_name='company',
            name='contactDetails_phoneNumberAreaCode',
            field=models.CharField(default=None, max_length=50, verbose_name='contactDetails_phoneNumberAreaCode'),
        ),
        migrations.AddField(
            model_name='company',
            name='contactDetails_phoneNumberCountryCode',
            field=models.CharField(default=None, max_length=10, verbose_name='contactDetails_phoneNumberCountryCode'),
        ),
        migrations.AddField(
            model_name='company',
            name='contactDetails_phoneNumberSubscriber',
            field=models.CharField(default=None, max_length=20, verbose_name='contactDetails_phoneNumberSubscriber'),
        ),
        migrations.AddField(
            model_name='company',
            name='contactDetails_salutation',
            field=models.CharField(default=None, max_length=10, verbose_name='contactDetails_salutation'),
        ),
        migrations.AddField(
            model_name='company',
            name='contactFormConfiguration_addressField',
            field=models.CharField(default=None, max_length=10, verbose_name='contactFormConfiguration_addressField'),
        ),
        migrations.AddField(
            model_name='company',
            name='contactFormConfiguration_applicationPackageCompletedField',
            field=models.CharField(default=None, max_length=10, verbose_name='contactFormConfiguration_applicationPackageCompletedField'),
        ),
        migrations.AddField(
            model_name='company',
            name='contactFormConfiguration_emailAddressField',
            field=models.CharField(default=None, max_length=10, verbose_name='contactFormConfiguration_emailAddressField'),
        ),
        migrations.AddField(
            model_name='company',
            name='contactFormConfiguration_employmentRelationshipField',
            field=models.CharField(default=None, max_length=10, verbose_name='contactFormConfiguration_employmentRelationshipField'),
        ),
        migrations.AddField(
            model_name='company',
            name='contactFormConfiguration_firstnameField',
            field=models.CharField(default=None, max_length=10, verbose_name='contactFormConfiguration_firstnameField'),
        ),
        migrations.AddField(
            model_name='company',
            name='contactFormConfiguration_freemiumSettings_duratio',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='contactFormConfiguration_incomeField',
            field=models.CharField(default=None, max_length=10, verbose_name='contactFormConfiguration_incomeField'),
        ),
        migrations.AddField(
            model_name='company',
            name='contactFormConfiguration_lastnameField',
            field=models.CharField(default=None, max_length=10, verbose_name='contactFormConfiguration_lastnameField'),
        ),
        migrations.AddField(
            model_name='company',
            name='contactFormConfiguration_messageField',
            field=models.CharField(default=None, max_length=40, verbose_name='contactFormConfiguration_messageField'),
        ),
        migrations.AddField(
            model_name='company',
            name='contactFormConfiguration_moveInDateField',
            field=models.CharField(default=None, max_length=40, verbose_name='contactFormConfiguration_moveInDateField'),
        ),
        migrations.AddField(
            model_name='company',
            name='contactFormConfiguration_numberOfPersonsField',
            field=models.CharField(default=None, max_length=40, verbose_name='contactFormConfiguration_numberOfPersonsField'),
        ),
        migrations.AddField(
            model_name='company',
            name='contactFormConfiguration_petsInHouseholdField',
            field=models.CharField(default=None, max_length=40, verbose_name='contactFormConfiguration_petsInHouseholdField'),
        ),
        migrations.AddField(
            model_name='company',
            name='contactFormConfiguration_phoneNumberField',
            field=models.CharField(default=None, max_length=40, verbose_name='contactFormConfiguration_phoneNumberField'),
        ),
        migrations.AddField(
            model_name='company',
            name='contactFormConfiguration_premiumProfileRequired',
            field=models.CharField(default=None, max_length=40, verbose_name='contactFormConfiguration_premiumProfileRequired'),
        ),
        migrations.AddField(
            model_name='company',
            name='contactFormConfiguration_salutationField',
            field=models.CharField(default=None, max_length=40, verbose_name='contactFormConfiguration_salutationField'),
        ),
    ]
