# Generated by Django 2.1.7 on 2019-03-18 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentdata', '0005_auto_20190318_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='imprintlink',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imprintLink_xlink_href', to='rentdata.Company'),
        ),
    ]
