# Generated by Django 2.1.7 on 2019-03-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentdata', '0002_auto_20190318_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='adLinkForJSONP_xlink_href',
            field=models.TextField(default=None, verbose_name='adLinkForJSONP_xlink_href'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='adLinkForXMLData_xlink_href',
            field=models.TextField(default=None, verbose_name='adLinkForXMLData_xlink_href'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='remove_id',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, unique=True, verbose_name='id'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='remove_modification',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='remove_publishDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='xlink_href',
            field=models.CharField(default=None, max_length=280, verbose_name='xlink_href'),
        ),
    ]
